//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transport$0 from "../../../../../quick-translate/internal/transport/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "translation": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = transport$0.TranslationDto.createFrom;
const $$createType1 = $Create.Nullable($$createType0);

configure();
