// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as transport$0 from "../../../../../quick-translate/internal/transport/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "error": string;
            "translating": void;
            "translation": transport$0.TranslationDto | null;
        }
    }
}
