// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Language {
    "tag": string;
    "name": string;
    "source": boolean;
    "target": boolean;
    "stable": boolean;

    /** Creates a new Language instance. */
    constructor($$source: Partial<Language> = {}) {
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = false;
        }
        if (!("target" in $$source)) {
            this["target"] = false;
        }
        if (!("stable" in $$source)) {
            this["stable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Language instance from a string or object.
     */
    static createFrom($$source: any = {}): Language {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Language($$parsedSource as Partial<Language>);
    }
}
