// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Switches to the given provider and translates the current text with it. Returns the whole state, because the languages that can be chosen belong to the provider and change with it. Returns an error if the provider can not be used, which leaves the previous one in place.
 */
export function ChangeProvider(slug: string): $CancellablePromise<$models.FullDto | null> {
    return $Call.ByID(1514413333, slug).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Sets the source language and translates the current text again. The target language is switched or dropped when it collides with the new source language, so it is part of the returned state. Returns an error if the language can not be chosen or the translation fails.
 */
export function ChangeSource(tag: string): $CancellablePromise<$models.TranslationDto | null> {
    return $Call.ByID(262670477, tag).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Sets the target language and translates the current text again. The source language is switched or dropped when it collides with the new target language, so it is part of the returned state. Returns an error if the language can not be chosen or the translation fails.
 */
export function ChangeTarget(tag: string): $CancellablePromise<$models.TranslationDto | null> {
    return $Call.ByID(3509587041, tag).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Writes the current translation to the clipboard. The window stays as it is, because the user decides when it goes away. Returns an error if there is nothing to copy or the clipboard can not be written.
 */
export function CopyTranslation(): $CancellablePromise<void> {
    return $Call.ByID(2303127940);
}

/**
 * Hides the window without stopping the application, which is what the frontend does when the user dismisses it.
 */
export function Hide(): $CancellablePromise<void> {
    return $Call.ByID(4083746016);
}

/**
 * Steps to the translation that was stored after the current one. Nothing is translated again, the stored translation is shown as it was made. Returns the whole state, because the provider and the languages of the stored translation are taken over with it. Returns an error if the history is disabled or can not be read.
 */
export function NextTranslation(): $CancellablePromise<$models.FullDto | null> {
    return $Call.ByID(3288416112).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Steps to the translation that was stored before the current one. Nothing is translated again, the stored translation is shown as it was made. Returns the whole state, because the provider and the languages of the stored translation are taken over with it. Returns an error if the history is disabled or can not be read.
 */
export function PreviousTranslation(): $CancellablePromise<$models.FullDto | null> {
    return $Call.ByID(1479812428).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Returns the whole state of the application in one call. Meant for the first render and for a frontend that was reloaded while a translation was on screen, so nothing has to be assembled from several calls that could answer out of order. Returns an error while the application can not translate yet, which is how a configuration that is not finished reaches the user instead of an empty window.
 */
export function State(): $CancellablePromise<$models.FullDto | null> {
    return $Call.ByID(61965493).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Switches the source and the target language and translates the current text in the other direction. Returns an error if the languages can not be switched, which leaves them unchanged.
 */
export function SwitchLanguages(): $CancellablePromise<$models.TranslationDto | null> {
    return $Call.ByID(684541183).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FullDto.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.TranslationDto.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
