// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * The whole state of the application. It is what every call answers with that can change more than the chosen languages, because the languages that can be chosen belong to the provider and change with it.
 */
export class FullDto {
    "Provider": ProviderDto | null;
    "Languages": LanguageDto | null;
    "Translation": TranslationDto | null;

    /** Creates a new FullDto instance. */
    constructor($$source: Partial<FullDto> = {}) {
        if (!("Provider" in $$source)) {
            this["Provider"] = null;
        }
        if (!("Languages" in $$source)) {
            this["Languages"] = null;
        }
        if (!("Translation" in $$source)) {
            this["Translation"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FullDto instance from a string or object.
     */
    static createFrom($$source: any = {}): FullDto {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Provider" in $$parsedSource) {
            $$parsedSource["Provider"] = $$createField0_0($$parsedSource["Provider"]);
        }
        if ("Languages" in $$parsedSource) {
            $$parsedSource["Languages"] = $$createField1_0($$parsedSource["Languages"]);
        }
        if ("Translation" in $$parsedSource) {
            $$parsedSource["Translation"] = $$createField2_0($$parsedSource["Translation"]);
        }
        return new FullDto($$parsedSource as Partial<FullDto>);
    }
}

/**
 * What the current provider offers. Everything in here changes only with the provider, which is why the chosen languages are not part of it. The two lists come in no promised order, so the frontend sorts them the way it wants to show them. Detection is nil for a provider that does not detect the source language on its own, and the two preferred tags are the ones the user configured, resolved against the lists so they can be pinned.
 */
export class LanguageDto {
    "PreferredSource": string;
    "PreferredTarget": string;
    "Detection": models$0.Language | null;
    "SourceLanguages": (models$0.Language | null)[];
    "TargetLanguages": (models$0.Language | null)[];

    /** Creates a new LanguageDto instance. */
    constructor($$source: Partial<LanguageDto> = {}) {
        if (!("PreferredSource" in $$source)) {
            this["PreferredSource"] = "";
        }
        if (!("PreferredTarget" in $$source)) {
            this["PreferredTarget"] = "";
        }
        if (!("Detection" in $$source)) {
            this["Detection"] = null;
        }
        if (!("SourceLanguages" in $$source)) {
            this["SourceLanguages"] = [];
        }
        if (!("TargetLanguages" in $$source)) {
            this["TargetLanguages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageDto instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageDto {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        const $$createField2_1 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Detection" in $$parsedSource) {
            $$parsedSource["Detection"] = $$createField1_0($$parsedSource["Detection"]);
        }
        if ("SourceLanguages" in $$parsedSource) {
            $$parsedSource["SourceLanguages"] = $$createField2_0($$parsedSource["SourceLanguages"]);
        }
        if ("TargetLanguages" in $$parsedSource) {
            $$parsedSource["TargetLanguages"] = $$createField2_1($$parsedSource["TargetLanguages"]);
        }
        return new LanguageDto($$parsedSource as Partial<LanguageDto>);
    }
}

/**
 * The providers that can be chosen. Current is the slug of the provider in use, and Providers holds the slugs of every provider that is configured well enough to be offered, the current one included.
 */
export class ProviderDto {
    "Current": string;
    "Providers": string[];

    /** Creates a new ProviderDto instance. */
    constructor($$source: Partial<ProviderDto> = {}) {
        if (!("Current" in $$source)) {
            this["Current"] = "";
        }
        if (!("Providers" in $$source)) {
            this["Providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDto instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderDto {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Providers" in $$parsedSource) {
            $$parsedSource["Providers"] = $$createField1_0($$parsedSource["Providers"]);
        }
        return new ProviderDto($$parsedSource as Partial<ProviderDto>);
    }
}

/**
 * The languages the user has chosen together with the translation that came out of them. The three tags point into the lists of the LanguageDto, so the frontend resolves them there instead of receiving their names twice. An empty tag means the language is not set, and a source tag of "auto" means the provider detects it, in which case DetectedSource carries what it found for the last translation.
 */
export class TranslationDto {
    "Source": string;
    "Target": string;
    "DetectedSource": string;
    "Translation": string;
    "HasPrevious": boolean;
    "HasNext": boolean;

    /** Creates a new TranslationDto instance. */
    constructor($$source: Partial<TranslationDto> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Target" in $$source)) {
            this["Target"] = "";
        }
        if (!("DetectedSource" in $$source)) {
            this["DetectedSource"] = "";
        }
        if (!("Translation" in $$source)) {
            this["Translation"] = "";
        }
        if (!("HasPrevious" in $$source)) {
            this["HasPrevious"] = false;
        }
        if (!("HasNext" in $$source)) {
            this["HasNext"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationDto instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationDto {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationDto($$parsedSource as Partial<TranslationDto>);
    }
}

// Private type creation functions
const $$createType0 = ProviderDto.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = LanguageDto.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = TranslationDto.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.Language.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
