// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeProvider(arg1) {
  return window['go']['transport']['Adapter']['ChangeProvider'](arg1);
}

export function ChangeSource(arg1) {
  return window['go']['transport']['Adapter']['ChangeSource'](arg1);
}

export function ChangeTarget(arg1) {
  return window['go']['transport']['Adapter']['ChangeTarget'](arg1);
}

export function CopyTranslation() {
  return window['go']['transport']['Adapter']['CopyTranslation']();
}

export function Hide() {
  return window['go']['transport']['Adapter']['Hide']();
}

export function NextTranslation() {
  return window['go']['transport']['Adapter']['NextTranslation']();
}

export function PreviousTranslation() {
  return window['go']['transport']['Adapter']['PreviousTranslation']();
}

export function State() {
  return window['go']['transport']['Adapter']['State']();
}

export function SwitchLanguages() {
  return window['go']['transport']['Adapter']['SwitchLanguages']();
}
