// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function ChangeProvider(arg1:string):Promise<transport.FullDto>;

export function ChangeSource(arg1:string):Promise<transport.TranslationDto>;

export function ChangeTarget(arg1:string):Promise<transport.TranslationDto>;

export function CopyTranslation():Promise<void>;

export function Hide():Promise<void>;

export function NextTranslation():Promise<transport.FullDto>;

export function PreviousTranslation():Promise<transport.FullDto>;

export function State():Promise<transport.FullDto>;

export function SwitchLanguages():Promise<transport.TranslationDto>;
